repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest suite
        entry: pytest
        language: system
        pass_filenames: false   
        always_run: true        
        types: [python]         
        args:                    
          - --maxfail=1
          - --disable-warnings
          - -q
